apiVersion: v1
kind: Namespace
metadata:
  name: test

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: server
  labels:
    purpose: server

---

apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    purpose: api

