language: python
python:
  3.8
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - kubectl version --client
  - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
  - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube

install:
  - minikube start --cpus 2 --memory 8192
  - minikube addons enable ingress
  - skaffold run
  - pip install -r ./test_script/requirements.txt

before_script:
  - kubectl get pods --all-namespaces
  - export MINIKUBE_IP=$(minikube ip)

script:
  - python ./test_script/test.py

before_deploy:
  - skaffold delete
  - minikube delete
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl

  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project $PROJECT_ID
  - gcloud config set compute/zone us-east1-b 
  - gcloud container clusters get-credentials $CLUSTER_NAME

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    brash: master