version: 0.2
env:
  SHA:
    SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION
phases:
  install:
    runtime-version:
      python: latest
    commands:
      - echo $SHA
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - apt-get update
      - apt-get -y install sudo
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - apt install conntrack
      - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
      - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube
  pre_build:
    commands:
      - minikube start --cpus 2 --memory 3000 --driver=none
      - minikube addons enable ingress
      - skaffold run
      - pip install -r ./test_script/requirements.txt
      - kubectl get pods --all-namespaces
      - kubectl describe nodes
      - export MINIKUBE_IP=$(minikube ip)

  build:
    commands:
      - python ./test_script/test.py

  post_build:
    commands:
      - skaffold delete
      - minikube delete