apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./namespace/*
      - ./k8s/*
  
build:
  local:
    push: false
  artifacts:
    - image: abbottqwq/chatbot-server
      context: chatbot-server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .

    - image: abbottqwq/redis-worker
      context: redis-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .
            
    - image: abbottqwq/chatbot-api
      context: chatbot-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .
