apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./namespace/*
      - ./k8s/*
      - ./test/*
  
build:
  local:
    push: false
  artifacts:
    - image: abbottqwq/chatbot-server
      context: chatbot-server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .

    - image: abbottqwq/redis-worker
      context: redis-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .
            
    - image: abbottqwq/chatbot-api
      context: chatbot-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .

    - image: abbottqwq/mongo-worker
      context: mongo-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .

    - image: abbottqwq/chatbot-test
      context: chatbot-test
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.py"
            dest: .

    - image: abbottqwq/chatbot-client
      context: chatbot-client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .