apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api-deployment
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
      - name: chatbot-api
        image: abbottqwq/chatbot-api
        ports:
        - containerPort: 5000

        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "2000Mi"
            cpu: "600m"
        
