apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-client-deployment
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      frontend: chatbot-client
  template:
    metadata:
      labels:
        frontend: chatbot-client
    spec:
      containers:
        - name: chatbot-client
          image: abbottqwq/chatbot-client
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
