apiVersion: v1
kind: Service
metadata:
  name: chatbot-server
  namespace: backend
  labels:
    rule: backend
spec:
  type: NodePort
  selector:
    backend: chatbot-server
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32100
  
