apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-worker-deployment
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      api: mongo-worker
  template:
    metadata:
      labels:
        api: mongo-worker
    spec:
      containers:
      - name: mongo-worker
        image: abbottqwq/mongo-worker
        resources:
          requests:
              memory: "32Mi"
              cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_HOST
            value: mongo-service
          - name: MONGO_PORT
            value: "27017"
          - name: REDIS_WORKER_SERVICE
            value: redis-worker-service
          - name: REDIS_WORKER_NAMESPACE
            value: api
          - name: REDIS_WORKER_PORT
            value: "5000"
